language: java
jdk:
  - oraclejdk8

git:
  submodules: false
  depth: 1

before_install:
  - git submodule update --init
  - ./build.py libs
  - pip install maxcdn

script: 
  - ./build.py compile
  - ./build.py css
  - ls -lah /home/travis/build/AnyChart/AnyChart/out/

after_success:
  - echo -e "Host $STATIC_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ./bin/upload_dev_files.sh
  - ./bin/upload_release_files.sh

notifications:
  slack: anychart-team:$SLACK_CHAT_KEY
